### ISSUE TITLE
Tests should be added for `--trace` across all lookups

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zdns#116]
This is a fairly big task.

**Comment by phillip-stephens** [comment]
Does anyone remember what `--trace` did? It's not in the current version of ZMap (HEAD of main) and I checked out `v1.0.0` and `v1.1.0` and it's not a CLI option in those either.

I'm going to close this for now since it doesn't seem to be a feature we have now, but please feel free to re-open if I'm missing some context and I can add this.

cc: @paul-pearce @zakird
