### ISSUE TITLE
alookup returns non ipv4 answers 

### ISSUE THREAD

**Issue by nikitaborisov** [zmap/zdns#163]
It seems to happen when a DNS server returns records of different types in the answer section to an `A` query:

```json
$ echo s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net | ~/go/bin/zdns a -iterative
{"name":"s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net","class":"IN","status":"NOERROR","timestamp":"2019-06-23T14:59:09+02:00","data":{"answers":[{"ttl":3600,"type":"A","class":"IN","name":"s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net","answer":"95.85.16.212"},{"ttl":3600,"type":"AAAA","class":"IN","name":"s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net","answer":"2a03:b0c0:0:1010::509:d001"}],"additionals":[],"authorities":[],"protocol":"udp","flags":{"response":true,"opcode":0,"authoritative":false,"truncated":false,"recursion_desired":false,"recursion_available":true,"authenticated":false,"checking_disabled":false,"error_code":0}}}
$ echo s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net | ~/go/bin/zdns alookup -iterative
{"name":"s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net","class":"IN","status":"NOERROR","timestamp":"2019-06-23T14:59:56+02:00","data":{"ipv4_addresses":["95.85.16.212","2a03:b0c0:0:1010::509:d001"]}}
```

Note that the second address in the `ipv4_addresses` field of `data` is actually an ipv6 address, returned as an `AAAA` record in the DNS query. I've also seen a server name show up in the `ipv4_addresses` field though I can't reproduce it right now.

**Comment by stklcode** [comment]
Apparently the nameserver (95.85.16.212 in this case) returns both A and AAAA in the answer section independent of the actual question and the tool (you might even try something weired like `s7hscpw1zwk8c8breqsiv6oiap07p6qz3dm0u5e3.ipleak.net. HS NAPTR` and will receive the `IN A`/`IN AAAA` tuple.

First of all I'd not consider this being a bug in ZDNS, as I would not expect any sanity checks on the answers. (in fact non-regular answers might contain far more information than expected behavior in some cases)

Second part is the _alookup_ module which simply takes the results without any checks either. One might discuss if the answers should be filtered at this point - most likely here: https://github.com/zmap/zdns/blob/c4cc17aedca28e491b6756683063bcc0733ace42/modules/alookup/alookup.go#L63-L70

Something like filtering result class and type (here IN/A) from the answer sections might be legit. However if the actual value if a declared "IN A" record is not a valid v4 IP ZDNS is definitely not to blame.

**Comment by zakird** [comment]
I agree that this operates as expected in the `a` module case since for those modules we simply want to return the server's exact response, but we probably do want to filter for `alookup`.

**Comment by stklcode** [comment]
> I've also seen a server name show up in the `ipv4_addresses` field though I can't reproduce it right now.

This happens when the first answer received is a valid `A` record and the second is something like `CNAME`, `NS`, `MX` where FQDNs are valid results.

That's because only the very first result of the answer set is checked.
