### ISSUE TITLE
FTBFS

### ISSUE THREAD

**Issue by d33tah** [zmap/zdns#205]
This appeared today:

```
 /root/go/src/github.com/zmap/zdns/modules/miekg/miekg.go:276:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
/root/go/src/github.com/zmap/zdns/modules/miekg/miekg.go:289:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
```

**Comment by zakird** [comment]
I suspect this your setup is not using `go.mod` correctly. That error arises from using an older version of zmap/dns than is specified in god.mod.

**Comment by zakird** [comment]
> @zakird Thanks for the reply! This is how I installed it and it used to work before:
> 
> ```
> > sudo docker run -ti golang
> [sudo] password d33tah@d33tah-pc: 
> root@9c22c9dc0b75:/go# go get github.com/zmap/zdns/zdns
> # github.com/zmap/zdns/modules/miekg
> src/github.com/zmap/zdns/modules/miekg/miekg.go:276:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
> src/github.com/zmap/zdns/modules/miekg/miekg.go:289:12: s.Client.LocalAddr undefined (type *dns.Client has no field or method LocalAddr)
> ```

What version of Go are you using? You want to be using Go 1.13.x. 

I understand that it worked before, but that's only because we hadn't changed the API of the backend library from the original version. So, your build wouldn't have broken until now despite it having used the less performant version.

**Comment by d33tah** [comment]
@zakird I'm using Go 1.13.3. Here's another Dockerfile to reproduce:

```
FROM ubuntu

RUN ( \
    apt-get update && apt-get -y install git wget && \
    wget -O- -nv https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz | \
    tar zxf - -C /opt && \
    ln /opt/go/bin/go /usr/bin/go && \
    GOROOT=/opt/go go get github.com/zmap/zdns/zdns \
)
```

**Comment by stklcode** [comment]
I also had to adjust my buildbot for Docker distribution (published as `stklcode/zdns` btw).

**Previously working versions (shortened)**
```
FROM golang AS builder
RUN go get -d github.com/zmap/go-iptree/blacklist && \
    go get -d github.com/zmap/zdns && \
    go build github.com/zmap/zdns/zdns
```
```
FROM golang AS builder
ARG hash=master
RUN mkdir ~/build && cd ~/build && \
    go mod init local/build && \
    go get -d "github.com/zmap/zdns@$hash"
RUN cd ~/build && \
    go build github.com/zmap/zdns/zdns
```
Both result in the same error as named above, i.e. wrong library version.

**Workaround (shortened)**
Clone from SCM and run build on source.
```
FROM golang AS builder
ARG hash=master
RUN git clone -n https://github.com/zmap/zdns.git src/github.com/zmap/zdns && \
    cd src/github.com/zmap/zdns && \
    git checkout "$hash"
RUN cd /go/src/github.com/zmap/zdns/zdns && \
    go build ./..
```

All built on latest 1.14.1, however the results are the same for 1.13.
Didn‘t have time to investigate the root cause, just needed a quick fix to get a fresh image.

**Comment by stklcode** [comment]
Apparently _go.sum_ lacks of entries for the latest DNS lib and this Go is falling back to -1

Adding the following solves the problem for me:
```
github.com/zmap/dns v1.1.28-zmap-2 h1:J9YfDoPWEK9SqoE+ukTCXn8IYJ+NlqM+eE2k2aRk8Ho=
github.com/zmap/dns v1.1.28-zmap-2/go.mod h1:KNUDUusw/aVsxyTYZM1oqvCicbwhgbNgztCETuNZ7xM=
```

**Comment by dadrian** [comment]
Unfortunately, `go get` doesn't respect replace statements. Furthermore, you can't easily `go get` code and build against it's `go.mod` and install the output, since `go get` in module mode stores files in some hidden directory in your home directory.

Here's a workaround Dockerfile, replace `alpine` with your preferred target OS:
```
FROM golang:1.14 AS builder
ENV GO111MODULE=on
WORKDIR /app
RUN git clone https://github.com/zmap/zdns
WORKDIR /app/zdns
RUN cd zdns && go build .

FROM alpine
COPY --from=builder /app/zdns/zdns/zdns /bin/zdns
```
