### ISSUE TITLE
Perform Multiple DNS lookup at once

### ISSUE THREAD

**Issue by AraCoders** [zmap/zdns#234]
Is there's a way in ZDNS to make A and AAAA record lookup at once?
something like `./zdns A,AAAA` ?

**Comment by zakird** [comment]
I think that `alookup` _might_ still allow this, but we're trying to pull it out if it's not already there, because it causes strange behavior with different global options, e.g., what status do you report in the global record if the A times out but the AAAA does not? Longterm, we'll allow you to pass in the command line what lookup you want done.
