### ISSUE TITLE
[Bug] The --local-addr option is invalid ?

### ISSUE THREAD

**Issue by Baoxd123** [zmap/zdns#481]
**Describe the bug**

Even if I added the local addr option following the help instruction, the local address did not change. 

**To Reproduce**

echo "censys.io" | ./zdns A --local-addr 128.192.12.101 //the ip can be anything, because all are invalid

**Expected behavior**
The src IP should be "128.192.12.101" but no change in the captured packets. 

**Screenshots**
Indeed, the local IP "128.192.12.188" does not exist in my machine, but I can specify it and nothing changed in the captured packets.
<img width="993" alt="image" src="https://github.com/user-attachments/assets/5389e1b5-4f45-47b0-9cd8-073f102bb675">

**Comment by phillip-stephens** [comment]
Hey @Baoxd123! Thanks for filing this issue.

You're correct, in this case we're ignoring your specified `--local-addr`. If you use `--verbosity=5`, you'll see some logs explaining why:
```
INFO[0000] using local addresses: [128.192.12.101]
INFO[0000] for non-iterative lookups, using external nameservers: 127.0.0.53:53
INFO[0000] for iterative lookups, using nameservers: 127.0.0.53:53
INFO[0000] no name server provided for external lookup, using  random external name server: 127.0.0.53:53
...
INFO[0000] none of the user-supplied local addresses could connect to name server 127.0.0.53:53, using local address 127.0.0.1
```

By default if you don't specify any external nameservers with `--name-servers`, we use whatever DNS resolver is configured in `/etc/resolver.conf`. It looks like for you that's `"resolver":"127.0.0.53"`. That's a loopback DNS resolver on your host machine. We wouldn't be able to connect to it using your specified `128.192.12.188` so instead of failing and leaving it to the user to try to figure out why, we switch to using a public-facing IP address for your host.
