### ISSUE TITLE
Please stop changing the values of the output!

### ISSUE THREAD

**Issue by brandonpoc** [zmap/zdns#69]
Note: please check the verbosity patch I just uploaded in the Issues section under the "CLI Option to silence listing of nameservers". It turns out that the verbosity level wasn't being used anywhere, as a) there were no checks on verbosity to decide output, and b) there was no SetLevel() for the logrus class translating the verbosity level to a log level.

Anyway, I have been writing scripts and software that depend on the zdns output yet zdns output has been changing an awful lot lately. First, the change from MX to MXLOOKUP with the way the JSON values were named, and various other small changes that borked the output (I don't remember what they were, but they changed).

And now - a change from a status of "SUCCESS" to "NOERROR". I was wondering why my script wasn't working, and it's because it was checking for SUCCESS. Why change from SUCCESS to NOERROR? Why keep changing output names and values? It's confusing. If it were changed from a major release to major release (version tree), then it may be acceptable. But changing from minor version to minor version consisting mainly of bug fixes and small functionality additions is just crazy. It's making it tough to use the software anytime it's upgraded.

Thanks
Brandon

**Comment by zakird** [comment]
While I appreciate the need for stable software, please note that this project is not versioned yet because it's so young. We've been working on it for about a month and we have not released a stable version.  It _will_ be semantically versioned and we _will_ follow semantic versioning rules when we do make a release. However, right now, the project is in initial development and it _is_ going to change until we formally release v.1. 

We hope to release v.1.0.0 here in the next week or two and for the most part, the output should be stable. I'm mostly waiting on some bug fixes from @bvandersloot before I tag.
